// <auto-generated />
using System;
using IGSPharma.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IGSPharma.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250609203139_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IGSPharma.Domain.Entities.Address", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.Changelog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Changelogs");
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BillingAddressId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsFirstOrder")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LoyaltyPointsEarned")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("RefundDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ShippingAddressId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BillingAddressId");

                    b.HasIndex("ShippingAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.OrderAuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderAuditLog");
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.OrderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDiscountApplied")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PrescriptionId")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.Prescription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DigitalSignature")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DoctorLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PrescriptionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.PrescriptionItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PrescriptionId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Refills")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("ProductId");

                    b.ToTable("PrescriptionItems");
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ActiveIngredients")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Dosage")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("InStock")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RegulatoryApprovalNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("RequiresPrescription")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "prescription-1",
                            ActiveIngredients = "[]",
                            Barcode = "prescription-1",
                            Category = "prescription",
                            Description = "Lisinopril 20mg is a prescription medication that requires a valid prescription from a licensed healthcare provider.",
                            Dosage = "3 tablet(s) daily",
                            ExpiryDate = new DateTime(2033, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(2911),
                            ImageUrl = "https://placehold.co/200x200?text=prescription+1",
                            InStock = true,
                            Manufacturer = "CureTech",
                            Name = "Lisinopril 20mg",
                            Price = 59.23m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = true,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = "prescription-2",
                            ActiveIngredients = "[]",
                            Barcode = "prescription-2",
                            Category = "prescription",
                            Description = "Atorvastatin 30mg is a prescription medication that requires a valid prescription from a licensed healthcare provider.",
                            Dosage = "1 tablet(s) daily",
                            ExpiryDate = new DateTime(2035, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3206),
                            ImageUrl = "https://placehold.co/200x200?text=prescription+2",
                            InStock = false,
                            Manufacturer = "VitaLabs",
                            Name = "Atorvastatin 30mg",
                            Price = 10.85m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = true,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = "prescription-3",
                            ActiveIngredients = "[]",
                            Barcode = "prescription-3",
                            Category = "prescription",
                            Description = "Levothyroxine 40mg is a prescription medication that requires a valid prescription from a licensed healthcare provider.",
                            Dosage = "1 tablet(s) daily",
                            ExpiryDate = new DateTime(2031, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3234),
                            ImageUrl = "https://placehold.co/200x200?text=prescription+3",
                            InStock = true,
                            Manufacturer = "CureTech",
                            Name = "Levothyroxine 40mg",
                            Price = 19.46m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = true,
                            StockQuantity = 26
                        },
                        new
                        {
                            Id = "prescription-4",
                            ActiveIngredients = "[]",
                            Barcode = "prescription-4",
                            Category = "prescription",
                            Description = "Metformin 50mg is a prescription medication that requires a valid prescription from a licensed healthcare provider.",
                            Dosage = "1 tablet(s) daily",
                            ExpiryDate = new DateTime(2033, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3256),
                            ImageUrl = "https://placehold.co/200x200?text=prescription+4",
                            InStock = true,
                            Manufacturer = "PharmaCorp",
                            Name = "Metformin 50mg",
                            Price = 10.34m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = true,
                            StockQuantity = 1
                        },
                        new
                        {
                            Id = "prescription-5",
                            ActiveIngredients = "[]",
                            Barcode = "prescription-5",
                            Category = "prescription",
                            Description = "Amlodipine 60mg is a prescription medication that requires a valid prescription from a licensed healthcare provider.",
                            Dosage = "3 tablet(s) daily",
                            ExpiryDate = new DateTime(2031, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3276),
                            ImageUrl = "https://placehold.co/200x200?text=prescription+5",
                            InStock = true,
                            Manufacturer = "CureTech",
                            Name = "Amlodipine 60mg",
                            Price = 47.73m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = true,
                            StockQuantity = 14
                        },
                        new
                        {
                            Id = "prescription-6",
                            ActiveIngredients = "[]",
                            Barcode = "prescription-6",
                            Category = "prescription",
                            Description = "Amlodipine 60mg is a prescription medication that requires a valid prescription from a licensed healthcare provider.",
                            Dosage = "3 tablet(s) daily",
                            ExpiryDate = new DateTime(2031, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3301),
                            ImageUrl = "https://placehold.co/200x200?text=prescription+6",
                            InStock = true,
                            Manufacturer = "PharmaCorp",
                            Name = "Amlodipine 60mg",
                            Price = 39.80m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = true,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = "prescription-7",
                            ActiveIngredients = "[]",
                            Barcode = "prescription-7",
                            Category = "prescription",
                            Description = "Amlodipine 60mg is a prescription medication that requires a valid prescription from a licensed healthcare provider.",
                            Dosage = "2 tablet(s) daily",
                            ExpiryDate = new DateTime(2035, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3322),
                            ImageUrl = "https://placehold.co/200x200?text=prescription+7",
                            InStock = true,
                            Manufacturer = "VitaLabs",
                            Name = "Amlodipine 60mg",
                            Price = 55.87m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = true,
                            StockQuantity = 88
                        },
                        new
                        {
                            Id = "prescription-8",
                            ActiveIngredients = "[]",
                            Barcode = "prescription-8",
                            Category = "prescription",
                            Description = "Amlodipine 60mg is a prescription medication that requires a valid prescription from a licensed healthcare provider.",
                            Dosage = "3 tablet(s) daily",
                            ExpiryDate = new DateTime(2027, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3341),
                            ImageUrl = "https://placehold.co/200x200?text=prescription+8",
                            InStock = false,
                            Manufacturer = "PharmaCorp",
                            Name = "Amlodipine 60mg",
                            Price = 34.65m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = true,
                            StockQuantity = 39
                        },
                        new
                        {
                            Id = "prescription-9",
                            ActiveIngredients = "[]",
                            Barcode = "prescription-9",
                            Category = "prescription",
                            Description = "Amlodipine 60mg is a prescription medication that requires a valid prescription from a licensed healthcare provider.",
                            Dosage = "3 tablet(s) daily",
                            ExpiryDate = new DateTime(2026, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3362),
                            ImageUrl = "https://placehold.co/200x200?text=prescription+9",
                            InStock = true,
                            Manufacturer = "PharmaCorp",
                            Name = "Amlodipine 60mg",
                            Price = 18.16m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = true,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = "prescription-10",
                            ActiveIngredients = "[]",
                            Barcode = "prescription-10",
                            Category = "prescription",
                            Description = "Amlodipine 60mg is a prescription medication that requires a valid prescription from a licensed healthcare provider.",
                            Dosage = "1 tablet(s) daily",
                            ExpiryDate = new DateTime(2026, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3486),
                            ImageUrl = "https://placehold.co/200x200?text=prescription+10",
                            InStock = true,
                            Manufacturer = "VitaLabs",
                            Name = "Amlodipine 60mg",
                            Price = 51.16m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = true,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = "otc-1",
                            ActiveIngredients = "[]",
                            Barcode = "otc-1",
                            Category = "otc",
                            Description = "Ibuprofen 200mg is an over-the-counter medication for temporary relief of minor aches and pains.",
                            Dosage = "2 tablet(s) daily",
                            ExpiryDate = new DateTime(2026, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3513),
                            ImageUrl = "https://placehold.co/200x200?text=otc+1",
                            InStock = false,
                            Manufacturer = "ConsumerHealth",
                            Name = "Ibuprofen 200mg",
                            Price = 28.16m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = "otc-2",
                            ActiveIngredients = "[]",
                            Barcode = "otc-2",
                            Category = "otc",
                            Description = "Acetaminophen 300mg is an over-the-counter medication for temporary relief of minor aches and pains.",
                            Dosage = "3 tablet(s) daily",
                            ExpiryDate = new DateTime(2035, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3535),
                            ImageUrl = "https://placehold.co/200x200?text=otc+2",
                            InStock = false,
                            Manufacturer = "ComfortPharm",
                            Name = "Acetaminophen 300mg",
                            Price = 46.84m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 36
                        },
                        new
                        {
                            Id = "otc-3",
                            ActiveIngredients = "[]",
                            Barcode = "otc-3",
                            Category = "otc",
                            Description = "Aspirin 400mg is an over-the-counter medication for temporary relief of minor aches and pains.",
                            Dosage = "1 tablet(s) daily",
                            ExpiryDate = new DateTime(2031, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3557),
                            ImageUrl = "https://placehold.co/200x200?text=otc+3",
                            InStock = true,
                            Manufacturer = "WellnessCare",
                            Name = "Aspirin 400mg",
                            Price = 52.41m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 59
                        },
                        new
                        {
                            Id = "otc-4",
                            ActiveIngredients = "[]",
                            Barcode = "otc-4",
                            Category = "otc",
                            Description = "Loratadine 500mg is an over-the-counter medication for temporary relief of minor aches and pains.",
                            Dosage = "2 tablet(s) daily",
                            ExpiryDate = new DateTime(2033, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3578),
                            ImageUrl = "https://placehold.co/200x200?text=otc+4",
                            InStock = true,
                            Manufacturer = "WellnessCare",
                            Name = "Loratadine 500mg",
                            Price = 22.25m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = "otc-5",
                            ActiveIngredients = "[]",
                            Barcode = "otc-5",
                            Category = "otc",
                            Description = "Cetirizine 600mg is an over-the-counter medication for temporary relief of minor aches and pains.",
                            Dosage = "3 tablet(s) daily",
                            ExpiryDate = new DateTime(2028, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3599),
                            ImageUrl = "https://placehold.co/200x200?text=otc+5",
                            InStock = true,
                            Manufacturer = "WellnessCare",
                            Name = "Cetirizine 600mg",
                            Price = 32.01m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 63
                        },
                        new
                        {
                            Id = "otc-6",
                            ActiveIngredients = "[]",
                            Barcode = "otc-6",
                            Category = "otc",
                            Description = "Cetirizine 600mg is an over-the-counter medication for temporary relief of minor aches and pains.",
                            Dosage = "1 tablet(s) daily",
                            ExpiryDate = new DateTime(2030, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3624),
                            ImageUrl = "https://placehold.co/200x200?text=otc+6",
                            InStock = false,
                            Manufacturer = "WellnessCare",
                            Name = "Cetirizine 600mg",
                            Price = 58.26m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 81
                        },
                        new
                        {
                            Id = "otc-7",
                            ActiveIngredients = "[]",
                            Barcode = "otc-7",
                            Category = "otc",
                            Description = "Cetirizine 600mg is an over-the-counter medication for temporary relief of minor aches and pains.",
                            Dosage = "1 tablet(s) daily",
                            ExpiryDate = new DateTime(2029, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3646),
                            ImageUrl = "https://placehold.co/200x200?text=otc+7",
                            InStock = true,
                            Manufacturer = "DailyHealth",
                            Name = "Cetirizine 600mg",
                            Price = 23.00m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = "otc-8",
                            ActiveIngredients = "[]",
                            Barcode = "otc-8",
                            Category = "otc",
                            Description = "Cetirizine 600mg is an over-the-counter medication for temporary relief of minor aches and pains.",
                            Dosage = "2 tablet(s) daily",
                            ExpiryDate = new DateTime(2029, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3740),
                            ImageUrl = "https://placehold.co/200x200?text=otc+8",
                            InStock = false,
                            Manufacturer = "WellnessCare",
                            Name = "Cetirizine 600mg",
                            Price = 35.74m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = "otc-9",
                            ActiveIngredients = "[]",
                            Barcode = "otc-9",
                            Category = "otc",
                            Description = "Cetirizine 600mg is an over-the-counter medication for temporary relief of minor aches and pains.",
                            Dosage = "2 tablet(s) daily",
                            ExpiryDate = new DateTime(2030, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3763),
                            ImageUrl = "https://placehold.co/200x200?text=otc+9",
                            InStock = true,
                            Manufacturer = "ReliefMed",
                            Name = "Cetirizine 600mg",
                            Price = 36.87m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 42
                        },
                        new
                        {
                            Id = "otc-10",
                            ActiveIngredients = "[]",
                            Barcode = "otc-10",
                            Category = "otc",
                            Description = "Cetirizine 600mg is an over-the-counter medication for temporary relief of minor aches and pains.",
                            Dosage = "2 tablet(s) daily",
                            ExpiryDate = new DateTime(2032, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3785),
                            ImageUrl = "https://placehold.co/200x200?text=otc+10",
                            InStock = false,
                            Manufacturer = "ReliefMed",
                            Name = "Cetirizine 600mg",
                            Price = 42.38m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 59
                        },
                        new
                        {
                            Id = "vitamins-1",
                            ActiveIngredients = "[]",
                            Barcode = "vitamins-1",
                            Category = "vitamins",
                            Description = "Vitamin D3 1000IU helps support overall health and wellness as part of a balanced diet.",
                            Dosage = "3 tablet(s) daily",
                            ExpiryDate = new DateTime(2026, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3809),
                            ImageUrl = "https://placehold.co/200x200?text=vitamins+1",
                            InStock = true,
                            Manufacturer = "VitaEssentials",
                            Name = "Vitamin D3 1000IU",
                            Price = 20.80m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = "vitamins-2",
                            ActiveIngredients = "[]",
                            Barcode = "vitamins-2",
                            Category = "vitamins",
                            Description = "Vitamin B12 1500IU helps support overall health and wellness as part of a balanced diet.",
                            Dosage = "3 tablet(s) daily",
                            ExpiryDate = new DateTime(2026, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3830),
                            ImageUrl = "https://placehold.co/200x200?text=vitamins+2",
                            InStock = true,
                            Manufacturer = "NaturalHealth",
                            Name = "Vitamin B12 1500IU",
                            Price = 20.64m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = "vitamins-3",
                            ActiveIngredients = "[]",
                            Barcode = "vitamins-3",
                            Category = "vitamins",
                            Description = "Multivitamin 2000IU helps support overall health and wellness as part of a balanced diet.",
                            Dosage = "1 tablet(s) daily",
                            ExpiryDate = new DateTime(2033, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3849),
                            ImageUrl = "https://placehold.co/200x200?text=vitamins+3",
                            InStock = true,
                            Manufacturer = "VitaEssentials",
                            Name = "Multivitamin 2000IU",
                            Price = 31.42m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 56
                        },
                        new
                        {
                            Id = "vitamins-4",
                            ActiveIngredients = "[]",
                            Barcode = "vitamins-4",
                            Category = "vitamins",
                            Description = "Vitamin C 2500IU helps support overall health and wellness as part of a balanced diet.",
                            Dosage = "1 tablet(s) daily",
                            ExpiryDate = new DateTime(2032, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3870),
                            ImageUrl = "https://placehold.co/200x200?text=vitamins+4",
                            InStock = false,
                            Manufacturer = "NaturalHealth",
                            Name = "Vitamin C 2500IU",
                            Price = 34.69m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = "vitamins-5",
                            ActiveIngredients = "[]",
                            Barcode = "vitamins-5",
                            Category = "vitamins",
                            Description = "Omega-3 3000IU helps support overall health and wellness as part of a balanced diet.",
                            Dosage = "3 tablet(s) daily",
                            ExpiryDate = new DateTime(2032, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3893),
                            ImageUrl = "https://placehold.co/200x200?text=vitamins+5",
                            InStock = true,
                            Manufacturer = "OrganicLife",
                            Name = "Omega-3 3000IU",
                            Price = 20.15m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 37
                        },
                        new
                        {
                            Id = "vitamins-6",
                            ActiveIngredients = "[]",
                            Barcode = "vitamins-6",
                            Category = "vitamins",
                            Description = "Omega-3 3000IU helps support overall health and wellness as part of a balanced diet.",
                            Dosage = "3 tablet(s) daily",
                            ExpiryDate = new DateTime(2030, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(3914),
                            ImageUrl = "https://placehold.co/200x200?text=vitamins+6",
                            InStock = true,
                            Manufacturer = "PureNutrition",
                            Name = "Omega-3 3000IU",
                            Price = 31.64m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = "vitamins-7",
                            ActiveIngredients = "[]",
                            Barcode = "vitamins-7",
                            Category = "vitamins",
                            Description = "Omega-3 3000IU helps support overall health and wellness as part of a balanced diet.",
                            Dosage = "1 tablet(s) daily",
                            ExpiryDate = new DateTime(2027, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(4174),
                            ImageUrl = "https://placehold.co/200x200?text=vitamins+7",
                            InStock = true,
                            Manufacturer = "OrganicLife",
                            Name = "Omega-3 3000IU",
                            Price = 19.98m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 76
                        },
                        new
                        {
                            Id = "vitamins-8",
                            ActiveIngredients = "[]",
                            Barcode = "vitamins-8",
                            Category = "vitamins",
                            Description = "Omega-3 3000IU helps support overall health and wellness as part of a balanced diet.",
                            Dosage = "2 tablet(s) daily",
                            ExpiryDate = new DateTime(2027, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(4199),
                            ImageUrl = "https://placehold.co/200x200?text=vitamins+8",
                            InStock = true,
                            Manufacturer = "VitaEssentials",
                            Name = "Omega-3 3000IU",
                            Price = 11.29m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 95
                        },
                        new
                        {
                            Id = "vitamins-9",
                            ActiveIngredients = "[]",
                            Barcode = "vitamins-9",
                            Category = "vitamins",
                            Description = "Omega-3 3000IU helps support overall health and wellness as part of a balanced diet.",
                            Dosage = "1 tablet(s) daily",
                            ExpiryDate = new DateTime(2026, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(4221),
                            ImageUrl = "https://placehold.co/200x200?text=vitamins+9",
                            InStock = true,
                            Manufacturer = "WellnessPlus",
                            Name = "Omega-3 3000IU",
                            Price = 17.57m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 51
                        },
                        new
                        {
                            Id = "vitamins-10",
                            ActiveIngredients = "[]",
                            Barcode = "vitamins-10",
                            Category = "vitamins",
                            Description = "Omega-3 3000IU helps support overall health and wellness as part of a balanced diet.",
                            Dosage = "3 tablet(s) daily",
                            ExpiryDate = new DateTime(2026, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(4243),
                            ImageUrl = "https://placehold.co/200x200?text=vitamins+10",
                            InStock = false,
                            Manufacturer = "NaturalHealth",
                            Name = "Omega-3 3000IU",
                            Price = 32.93m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = "personal-care-1",
                            ActiveIngredients = "[]",
                            Barcode = "personal-care-1",
                            Category = "personal-care",
                            Description = "Hand Sanitizer is designed for daily personal hygiene and self-care.",
                            ExpiryDate = new DateTime(2030, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(4266),
                            ImageUrl = "https://placehold.co/200x200?text=personal-care+1",
                            InStock = true,
                            Manufacturer = "CleanLiving",
                            Name = "Hand Sanitizer",
                            Price = 13.67m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 76
                        },
                        new
                        {
                            Id = "personal-care-2",
                            ActiveIngredients = "[]",
                            Barcode = "personal-care-2",
                            Category = "personal-care",
                            Description = "Moisturizing Lotion is designed for daily personal hygiene and self-care.",
                            ExpiryDate = new DateTime(2026, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(4286),
                            ImageUrl = "https://placehold.co/200x200?text=personal-care+2",
                            InStock = true,
                            Manufacturer = "CleanLiving",
                            Name = "Moisturizing Lotion",
                            Price = 26.86m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 41
                        },
                        new
                        {
                            Id = "personal-care-3",
                            ActiveIngredients = "[]",
                            Barcode = "personal-care-3",
                            Category = "personal-care",
                            Description = "Sunscreen is designed for daily personal hygiene and self-care.",
                            ExpiryDate = new DateTime(2032, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(4305),
                            ImageUrl = "https://placehold.co/200x200?text=personal-care+3",
                            InStock = true,
                            Manufacturer = "PureSkin",
                            Name = "Sunscreen",
                            Price = 19.31m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 97
                        },
                        new
                        {
                            Id = "personal-care-4",
                            ActiveIngredients = "[]",
                            Barcode = "personal-care-4",
                            Category = "personal-care",
                            Description = "Dental Floss is designed for daily personal hygiene and self-care.",
                            ExpiryDate = new DateTime(2027, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(4331),
                            ImageUrl = "https://placehold.co/200x200?text=personal-care+4",
                            InStock = false,
                            Manufacturer = "DailyCare",
                            Name = "Dental Floss",
                            Price = 28.48m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 86
                        },
                        new
                        {
                            Id = "personal-care-5",
                            ActiveIngredients = "[]",
                            Barcode = "personal-care-5",
                            Category = "personal-care",
                            Description = "Antiseptic Spray is designed for daily personal hygiene and self-care.",
                            ExpiryDate = new DateTime(2029, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(4350),
                            ImageUrl = "https://placehold.co/200x200?text=personal-care+5",
                            InStock = true,
                            Manufacturer = "PureSkin",
                            Name = "Antiseptic Spray",
                            Price = 25.54m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = "personal-care-6",
                            ActiveIngredients = "[]",
                            Barcode = "personal-care-6",
                            Category = "personal-care",
                            Description = "Antiseptic Spray is designed for daily personal hygiene and self-care.",
                            ExpiryDate = new DateTime(2027, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(4470),
                            ImageUrl = "https://placehold.co/200x200?text=personal-care+6",
                            InStock = true,
                            Manufacturer = "DailyCare",
                            Name = "Antiseptic Spray",
                            Price = 40.48m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 31
                        },
                        new
                        {
                            Id = "personal-care-7",
                            ActiveIngredients = "[]",
                            Barcode = "personal-care-7",
                            Category = "personal-care",
                            Description = "Antiseptic Spray is designed for daily personal hygiene and self-care.",
                            ExpiryDate = new DateTime(2031, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(4490),
                            ImageUrl = "https://placehold.co/200x200?text=personal-care+7",
                            InStock = false,
                            Manufacturer = "DailyCare",
                            Name = "Antiseptic Spray",
                            Price = 10.10m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 72
                        },
                        new
                        {
                            Id = "personal-care-8",
                            ActiveIngredients = "[]",
                            Barcode = "personal-care-8",
                            Category = "personal-care",
                            Description = "Antiseptic Spray is designed for daily personal hygiene and self-care.",
                            ExpiryDate = new DateTime(2031, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(4509),
                            ImageUrl = "https://placehold.co/200x200?text=personal-care+8",
                            InStock = true,
                            Manufacturer = "HygieneFirst",
                            Name = "Antiseptic Spray",
                            Price = 42.29m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 21
                        },
                        new
                        {
                            Id = "personal-care-9",
                            ActiveIngredients = "[]",
                            Barcode = "personal-care-9",
                            Category = "personal-care",
                            Description = "Antiseptic Spray is designed for daily personal hygiene and self-care.",
                            ExpiryDate = new DateTime(2033, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(4527),
                            ImageUrl = "https://placehold.co/200x200?text=personal-care+9",
                            InStock = true,
                            Manufacturer = "CleanLiving",
                            Name = "Antiseptic Spray",
                            Price = 13.37m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = "personal-care-10",
                            ActiveIngredients = "[]",
                            Barcode = "personal-care-10",
                            Category = "personal-care",
                            Description = "Antiseptic Spray is designed for daily personal hygiene and self-care.",
                            ExpiryDate = new DateTime(2031, 6, 9, 20, 31, 38, 847, DateTimeKind.Local).AddTicks(4547),
                            ImageUrl = "https://placehold.co/200x200?text=personal-care+10",
                            InStock = true,
                            Manufacturer = "DailyCare",
                            Name = "Antiseptic Spray",
                            Price = 48.36m,
                            RegulatoryApprovalNumber = "",
                            RequiresPrescription = false,
                            StockQuantity = 9
                        });
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.ProductBatch", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ManufacturingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductBatch");
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("PrescriptionAccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.Address", b =>
                {
                    b.HasOne("IGSPharma.Domain.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.Order", b =>
                {
                    b.HasOne("IGSPharma.Domain.Entities.Address", "BillingAddress")
                        .WithMany()
                        .HasForeignKey("BillingAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IGSPharma.Domain.Entities.Address", "ShippingAddress")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IGSPharma.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BillingAddress");

                    b.Navigation("ShippingAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.OrderAuditLog", b =>
                {
                    b.HasOne("IGSPharma.Domain.Entities.Order", "Order")
                        .WithMany("AuditLogs")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("IGSPharma.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IGSPharma.Domain.Entities.Prescription", "Prescription")
                        .WithMany()
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IGSPharma.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Prescription");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("IGSPharma.Domain.Entities.User", "User")
                        .WithMany("Prescriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.PrescriptionItem", b =>
                {
                    b.HasOne("IGSPharma.Domain.Entities.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IGSPharma.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prescription");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.ProductBatch", b =>
                {
                    b.HasOne("IGSPharma.Domain.Entities.Product", "Product")
                        .WithMany("Batches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.Order", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.Product", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("IGSPharma.Domain.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");

                    b.Navigation("Prescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
