// <auto-generated />
using IGSPharma.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IGSPharma.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250521094054_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.5.24306.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IGSPharma.Domain.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Dosage")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("InStock")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("RequiresPrescription")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "prescription-1",
                            Category = "prescription",
                            Description = "Lisinopril 20mg is a prescription medication that requires a valid prescription from a licensed healthcare provider.",
                            Dosage = "3 tablet(s) daily",
                            ImageUrl = "https://placehold.co/200x200?text=prescription+1",
                            InStock = true,
                            Manufacturer = "CureTech",
                            Name = "Lisinopril 20mg",
                            Price = 59.23m,
                            RequiresPrescription = true
                        },
                        new
                        {
                            Id = "prescription-2",
                            Category = "prescription",
                            Description = "Atorvastatin 30mg is a prescription medication that requires a valid prescription from a licensed healthcare provider.",
                            Dosage = "1 tablet(s) daily",
                            ImageUrl = "https://placehold.co/200x200?text=prescription+2",
                            InStock = false,
                            Manufacturer = "PharmaCorp",
                            Name = "Atorvastatin 30mg",
                            Price = 46.94m,
                            RequiresPrescription = true
                        },
                        new
                        {
                            Id = "prescription-3",
                            Category = "prescription",
                            Description = "Levothyroxine 40mg is a prescription medication that requires a valid prescription from a licensed healthcare provider.",
                            Dosage = "3 tablet(s) daily",
                            ImageUrl = "https://placehold.co/200x200?text=prescription+3",
                            InStock = true,
                            Manufacturer = "HealthRx",
                            Name = "Levothyroxine 40mg",
                            Price = 19.74m,
                            RequiresPrescription = true
                        },
                        new
                        {
                            Id = "prescription-4",
                            Category = "prescription",
                            Description = "Metformin 50mg is a prescription medication that requires a valid prescription from a licensed healthcare provider.",
                            Dosage = "1 tablet(s) daily",
                            ImageUrl = "https://placehold.co/200x200?text=prescription+4",
                            InStock = true,
                            Manufacturer = "CureTech",
                            Name = "Metformin 50mg",
                            Price = 19.46m,
                            RequiresPrescription = true
                        },
                        new
                        {
                            Id = "prescription-5",
                            Category = "prescription",
                            Description = "Amlodipine 60mg is a prescription medication that requires a valid prescription from a licensed healthcare provider.",
                            Dosage = "1 tablet(s) daily",
                            ImageUrl = "https://placehold.co/200x200?text=prescription+5",
                            InStock = true,
                            Manufacturer = "CureTech",
                            Name = "Amlodipine 60mg",
                            Price = 38.33m,
                            RequiresPrescription = true
                        },
                        new
                        {
                            Id = "otc-1",
                            Category = "otc",
                            Description = "Ibuprofen 200mg is an over-the-counter medication for temporary relief of minor aches and pains.",
                            Dosage = "3 tablet(s) daily",
                            ImageUrl = "https://placehold.co/200x200?text=otc+1",
                            InStock = false,
                            Manufacturer = "ConsumerHealth",
                            Name = "Ibuprofen 200mg",
                            Price = 18.00m,
                            RequiresPrescription = false
                        },
                        new
                        {
                            Id = "otc-2",
                            Category = "otc",
                            Description = "Acetaminophen 300mg is an over-the-counter medication for temporary relief of minor aches and pains.",
                            Dosage = "3 tablet(s) daily",
                            ImageUrl = "https://placehold.co/200x200?text=otc+2",
                            InStock = true,
                            Manufacturer = "ComfortPharm",
                            Name = "Acetaminophen 300mg",
                            Price = 47.73m,
                            RequiresPrescription = false
                        },
                        new
                        {
                            Id = "otc-3",
                            Category = "otc",
                            Description = "Aspirin 400mg is an over-the-counter medication for temporary relief of minor aches and pains.",
                            Dosage = "2 tablet(s) daily",
                            ImageUrl = "https://placehold.co/200x200?text=otc+3",
                            InStock = false,
                            Manufacturer = "ComfortPharm",
                            Name = "Aspirin 400mg",
                            Price = 36.05m,
                            RequiresPrescription = false
                        },
                        new
                        {
                            Id = "otc-4",
                            Category = "otc",
                            Description = "Loratadine 500mg is an over-the-counter medication for temporary relief of minor aches and pains.",
                            Dosage = "2 tablet(s) daily",
                            ImageUrl = "https://placehold.co/200x200?text=otc+4",
                            InStock = false,
                            Manufacturer = "ConsumerHealth",
                            Name = "Loratadine 500mg",
                            Price = 47.92m,
                            RequiresPrescription = false
                        },
                        new
                        {
                            Id = "otc-5",
                            Category = "otc",
                            Description = "Cetirizine 600mg is an over-the-counter medication for temporary relief of minor aches and pains.",
                            Dosage = "2 tablet(s) daily",
                            ImageUrl = "https://placehold.co/200x200?text=otc+5",
                            InStock = true,
                            Manufacturer = "DailyHealth",
                            Name = "Cetirizine 600mg",
                            Price = 55.87m,
                            RequiresPrescription = false
                        },
                        new
                        {
                            Id = "vitamins-1",
                            Category = "vitamins",
                            Description = "Vitamin D3 1000IU helps support overall health and wellness as part of a balanced diet.",
                            Dosage = "2 tablet(s) daily",
                            ImageUrl = "https://placehold.co/200x200?text=vitamins+1",
                            InStock = true,
                            Manufacturer = "NaturalHealth",
                            Name = "Vitamin D3 1000IU",
                            Price = 56.59m,
                            RequiresPrescription = false
                        },
                        new
                        {
                            Id = "vitamins-2",
                            Category = "vitamins",
                            Description = "Vitamin B12 1500IU helps support overall health and wellness as part of a balanced diet.",
                            Dosage = "1 tablet(s) daily",
                            ImageUrl = "https://placehold.co/200x200?text=vitamins+2",
                            InStock = false,
                            Manufacturer = "VitaEssentials",
                            Name = "Vitamin B12 1500IU",
                            Price = 47.86m,
                            RequiresPrescription = false
                        },
                        new
                        {
                            Id = "vitamins-3",
                            Category = "vitamins",
                            Description = "Multivitamin 2000IU helps support overall health and wellness as part of a balanced diet.",
                            Dosage = "3 tablet(s) daily",
                            ImageUrl = "https://placehold.co/200x200?text=vitamins+3",
                            InStock = true,
                            Manufacturer = "NaturalHealth",
                            Name = "Multivitamin 2000IU",
                            Price = 18.16m,
                            RequiresPrescription = false
                        },
                        new
                        {
                            Id = "vitamins-4",
                            Category = "vitamins",
                            Description = "Vitamin C 2500IU helps support overall health and wellness as part of a balanced diet.",
                            Dosage = "3 tablet(s) daily",
                            ImageUrl = "https://placehold.co/200x200?text=vitamins+4",
                            InStock = true,
                            Manufacturer = "WellnessPlus",
                            Name = "Vitamin C 2500IU",
                            Price = 10.55m,
                            RequiresPrescription = false
                        },
                        new
                        {
                            Id = "vitamins-5",
                            Category = "vitamins",
                            Description = "Omega-3 3000IU helps support overall health and wellness as part of a balanced diet.",
                            Dosage = "1 tablet(s) daily",
                            ImageUrl = "https://placehold.co/200x200?text=vitamins+5",
                            InStock = true,
                            Manufacturer = "NaturalHealth",
                            Name = "Omega-3 3000IU",
                            Price = 16.41m,
                            RequiresPrescription = false
                        },
                        new
                        {
                            Id = "personal-care-1",
                            Category = "personal-care",
                            Description = "Hand Sanitizer is designed for daily personal hygiene and self-care.",
                            ImageUrl = "https://placehold.co/200x200?text=personal-care+1",
                            InStock = false,
                            Manufacturer = "HygieneFirst",
                            Name = "Hand Sanitizer",
                            Price = 28.16m,
                            RequiresPrescription = false
                        },
                        new
                        {
                            Id = "personal-care-2",
                            Category = "personal-care",
                            Description = "Moisturizing Lotion is designed for daily personal hygiene and self-care.",
                            ImageUrl = "https://placehold.co/200x200?text=personal-care+2",
                            InStock = false,
                            Manufacturer = "CareProducts",
                            Name = "Moisturizing Lotion",
                            Price = 12.72m,
                            RequiresPrescription = false
                        },
                        new
                        {
                            Id = "personal-care-3",
                            Category = "personal-care",
                            Description = "Sunscreen is designed for daily personal hygiene and self-care.",
                            ImageUrl = "https://placehold.co/200x200?text=personal-care+3",
                            InStock = false,
                            Manufacturer = "CleanLiving",
                            Name = "Sunscreen",
                            Price = 46.84m,
                            RequiresPrescription = false
                        },
                        new
                        {
                            Id = "personal-care-4",
                            Category = "personal-care",
                            Description = "Dental Floss is designed for daily personal hygiene and self-care.",
                            ImageUrl = "https://placehold.co/200x200?text=personal-care+4",
                            InStock = true,
                            Manufacturer = "DailyCare",
                            Name = "Dental Floss",
                            Price = 59.26m,
                            RequiresPrescription = false
                        },
                        new
                        {
                            Id = "personal-care-5",
                            Category = "personal-care",
                            Description = "Antiseptic Spray is designed for daily personal hygiene and self-care.",
                            ImageUrl = "https://placehold.co/200x200?text=personal-care+5",
                            InStock = true,
                            Manufacturer = "CareProducts",
                            Name = "Antiseptic Spray",
                            Price = 52.41m,
                            RequiresPrescription = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
